name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 14]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hexojs/hexo-starter
      - uses: actions/checkout@v2
        with:
          path: themes/icarus
      - uses: actions/checkout@v2
        with:
          repository: SukkaLab/hexo-many-posts
          path: source/_posts/hexo-many-posts
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-cache
          restore-keys: npm-cache
      - run: npm install
      - run: >
          npm install $(node -e "const deps=require('./themes/icarus/package.json').dependencies;
          console.log(Object.keys(deps).map(key=>key+'@'+deps[key]).join(' '));")
      - run: >
          npm install $(node -e "const deps=require('./themes/icarus/package.json').peerDependencies;
          console.log(Object.keys(deps).map(key=>key+'@'+deps[key]).join(' '));")
      - run: npx hexo config theme icarus
      - run: time NODE_ENV=production npx hexo g -b
